### ISSUE TITLE
Hangs when using replicaset

### ISSUE THREAD

**Issue by wmertens** [jdesboeufs/connect-mongo#227]
Hi,

I have a 2-node+1 arbiter replicaset, and connect-mongo often hangs communicating with it.

My mongo connection string (the `url` option) is `mongodb://192.168.1.11,192.168.1.12,192.168.1.14/mydb?replicaSet=rs0`.

Things work fine after starting, until something happens (I'm suspecting another node that is connecting to the session store), and then the `store.get()` function never returns.

To be precise, execution goes to https://github.com/kcbanner/connect-mongo/blob/7a1b614b93b9274a423a1acc40eecfc5a6a08b32/src/index.js#L193 and then hangs. No error happens. (should there be a timeout on that?)

I'm using MongoDB 3.2.4 on OS X, and my app uses Mongoose but I don't pass that to connect-mongo.

**Comment by wmertens** [comment]
I also noticed this bluebird warning:
```
Warning: a promise was created in a handler but was not returned from it
    at MongoStore.touch (/myapp/node_modules/connect-mongo/src/index.js:279:18)
    at ServerResponse.end (/myapp/node_modules/express-session/index.js:332:15)
    at ServerResponse.send (/myapp/node_modules/express/lib/response.js:205:10)
    at sendResObj (routes.js:77:7)
    at routes.js:86:18
    at promiseJson.js:18:8
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
```
Maybe something fails in that call and subsequent calls on the same connection hang?

**Comment by wmertens** [comment]
I switched to reusing the Mongoose connection and that seems to have fixed it, but I'm not sure. I'll update tomorrow.

**Comment by wmertens** [comment]
Indeed, using the mongoose connection I still don't have issues, and normally I would have had them by now.

I will leave this issue open to make sure you know of it, perhaps the documentation should be adjusted to recommend using the Mongoose connection when using a Replica Set?v
