### ISSUE TITLE
ReferenceError: Unknown plugin "transform-object-assign"

### ISSUE THREAD

**Issue by miqmago** [jdesboeufs/connect-mongo#233]
I'm using `connect-mongo` in an es6 app, compiled with `babel-node --presets=es2015`

I'm getting this error:

```
ReferenceError: Unknown plugin "transform-object-assign" specified in "/server/node_modules/connect-mongo/.babelrc" at 4, attempted to resolve relative to "/server/node_modules/connect-mongo"
    at /server/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204:17
    at Array.map (native)
    at Function.normalisePlugins (/server/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/server/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.addConfig (/server/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/server/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/server/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at compile (/server/node_modules/babel-register/lib/node.js:112:69)
    at loader (/server/node_modules/babel-register/lib/node.js:158:14)
    at Object.require.extensions.(anonymous function) [as .js] (/server/node_modules/babel-register/lib/node.js:168:7)
```

It's solved by installing this npm plugin:

```
npm install babel-plugin-transform-object-assign --save
```

Could it be solved by adding a dependency on this plugin?

**Comment by jdesboeufs** [comment]
This is already a "devDependency".

**Comment by jdesboeufs** [comment]
If your runtime is not ES6 compliant, you can refer to this:

**Comment by henfj** [comment]
dependencies for ant.design

$ npm install babel-plugin-transform-object-assign --save
$ npm install babel-plugin-transform-object-assign --save
$ npm install babel-plugin-transform-object-rest-spread --save-dev

and add the css:

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/antd/2.10.2/antd.css">
