### ISSUE TITLE
How best to catch exception thrown by MongoDB such as " MongoError: topology was destroyed"

### ISSUE THREAD

**Issue by shiwanlin** [jdesboeufs/connect-mongo#237]
We have run into this a few times and wonder anyone has any suggestion as to where best to put a try-catch block to properly handle the request related to the Mongo exception, e.g. returning a 500? Thank you in advance!

 MongoError: topology was destroyed
 at Server.update (/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:946:49)
 at Server.update (/app/node_modules/mongoose/node_modules/mongodb/lib/server.js:317:17)
 at updateDocuments (/app/node_modules/mongoose/node_modules/mongodb/lib/collection.js:833:19)
 at Collection.update (/app/node_modules/mongoose/node_modules/mongodb/lib/collection.js:863:44)
 at /app/node_modules/connect-mongo/lib/connect-mongo.js:360:18
 at MongoStore.getCollection (/app/node_modules/connect-mongo/lib/connect-mongo.js:216:11)
 at MongoStore.set (/app/node_modules/connect-mongo/lib/connect-mongo.js:358:10)
 at Session.save (/app/node_modules/express-session/session/session.js:71:25)
 at Session.save (/app/node_modules/express-session/index.js:327:15)
 at ServerResponse.end (/app/node_modules/express-session/index.js:285:21)
 at ServerResponse.res.end (/app/node_modules/compression/index.js:98:20)
 at Array.write (/app/node_modules/express/node_modules/finalhandler/index.js:137:9)
 at listener (/app/node_modules/express/node_modules/on-finished/index.js:169:15)
 at onFinish (/app/node_modules/express/node_modules/on-finished/index.js:100:5)
 at callback (/app/node_modules/express/node_modules/on-finished/node_modules/ee-first/index.js:55:10)
 at IncomingMessage.onevent (/app/node_modules/express/node_modules/on-finished/node_modules/ee-first/index.js:93:5)

**Comment by rkrauskopf** [comment]
@shiwanlin Hi, I'm seeing the same issue intermittently on my project as well. Were you ever able to resolve this?

**Comment by shiwanlin** [comment]
@rkrauskopf No, no progress at this point, unfortunately.

**Comment by demsey2** [comment]
@rkrauskopf @shiwanlin any update on this, I am looking for something similar?
