### ISSUE TITLE
Library throwing errors

### ISSUE THREAD

**Issue by abhiCR7** [jdesboeufs/connect-mongo#249]
We are using "connect-mongo": "~0.8"
and suddenly it is throwing these error messages

`node_modules/connect-mongo/node_modules/debug/debug.js:126
  debug.color = selectColor(namespae);
                            ^
ReferenceError: namespae is not defined
    at createDebug (/home/ubuntu/workspace/lms/node_modules/connect-mongo/node_modules/debug/debug.js:126:29)
    at Object.<anonymous> (/home/ubuntu/workspace/lms/node_modules/connect-mongo/lib/connect-mongo.js:10:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.cls_wrapMethod (/home/ubuntu/workspace/lms/node_modules/newrelic/lib/shimmer.js:256:38)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/workspace/lms/config/express.js:8:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.cls_wrapMethod (/home/ubuntu/workspace/lms/node_modules/newrelic/lib/shimmer.js:256:38)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/workspace/lms/server.js:36:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
error: Forever detected script exited with code: 1
error: Script restart attempt #1``

**Comment by jdesboeufs** [comment]
Hello,

debug is no more used in connect-mongo.
You should upgrade your connect-mongo version ;)
Le mer. 14 déc. 2016 à 08:23, Abhishek Todmal <notifications@github.com> a
écrit :
