### ISSUE TITLE
TypeError: Cannot read property 'Store' of undefined

### ISSUE THREAD

**Issue by Christian510** [jdesboeufs/connect-mongo#376]
I have only seen one or two references to this issue and they are quite old and not helpful.  I continue to get this error after trying other variations.  Here is the error from the command line:
```
/Users/macbook/.../node_modules/connect-mongo/src/index.js:57
  const Store = connect.Store || connect.session.Store

TypeError: Cannot read property 'Store' of undefined
    at module.exports (/Users/macbook/Documents/web-development/sessions_cookie_practice/node_modules/connect-mongo/src/index.js:57:50)
    at Object.<anonymous> (/Users/macbook/Documents/web-development/sessions_cookie_practice/app.js:8:42)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
 I tried using mongoose.  That didn't work- same error.  I checked to make sure the versions connect-mongo requires is correct in my package.json file.  I'm out of ideas. 
Her is my code:
```
require('dotenv').config();
const path = require('path');
const express = require('express');
const bodyParser = require('body-parser');
const mongodb = require('mongodb');
const MongoClient = mongodb.MongoClient;
const session = require('express-sessions');
var MongoStore = require('connect-mongo')(session);
// const getDb = require('./util/database').getDb;

const app = express();

// VIEW ENGINE SETUP
app.set('view engine', 'ejs');
app.set('views', 'views');

app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, 'public')));
// app.use(express.json);
// app.use(express.urlencoded({extended: false}));

const url = "mongodb+srv://<name>:<password>@sessionsdb.pwcbi.mongodb.net/SessionsDb?retryWrites=true&w=majority";
// const options = {
//     useNewUrlParser: true,
//     useUnifiedTopology: true
// };

const mongoClient = MongoClient.connect(
    url,
    {
        useNewUrlParser: true,
        useUnifiedTopology: true
    })

const sessionStore = new MongoStore({
    url: mongoClient,
    collection: 'sessions',
})

app.use(session({
    secret: "climb hard!",
    store: sessionStore,
    resave: false,
    saveUninitialized: true,
    cookie: {
        maxAge: 1000 * 60 * 60 * 24 // EQUALS 1 DAY ( 1 DAY * 24 HR/1 DAY * 60 MIN/1 HR)
    }

}))
```

**Comment by Christian510** [comment]
I saw a version where one just passed to the mongostore a db reference.  Tried that with no luck!

**Comment by Christian510** [comment]
Well, this is embarrassing. I figured out the problem.  connect.session.Store was returning undefined because I was passing it the wrong package.  I accidentally installed "express-sessions" vs. "express-session".  Blah!!!
