### ISSUE TITLE
Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency

### ISSUE THREAD

**Issue by augnustin** [jdesboeufs/connect-mongo#386]
Hello,

I have this kind of weir error using connect-mongo:

```
[1] (node:6908) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
[1]     at emitCircularRequireWarning (node:internal/modules/cjs/loader:698:11)
[1]     at Object.get (node:internal/modules/cjs/loader:712:5)
[1]     at Object.<anonymous> (/novatube/node_modules/connect-mongo/node_modules/mongodb/lib/operations/operation.js:4:38)
[1]     at Module._compile (node:internal/modules/cjs/loader:1108:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
[1]     at Module.load (node:internal/modules/cjs/loader:973:32)
[1]     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
[1]     at Module.require (node:internal/modules/cjs/loader:997:19)
[1]     at require (node:internal/modules/cjs/helpers:92:18)
[1]     at Object.<anonymous> (/novatube/node_modules/connect-mongo/node_modules/mongodb/lib/operations/execute_operation.js:4:16)
[1]     at Module._compile (node:internal/modules/cjs/loader:1108:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
[1]     at Module.load (node:internal/modules/cjs/loader:973:32)
[1]     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
[1]     at Module.require (node:internal/modules/cjs/loader:997:19)
[1]     at require (node:internal/modules/cjs/helpers:92:18)

```

Here's the code:

```
const session = require('express-session');
const MongoStore = require('connect-mongo')(session);
app.use(session({
  store: new MongoStore({ url: MONGO_URL, autoReconnect: true }),
});
```
I also tried:

```
const session = require('express-session');
const MongoStore = require('connect-mongo')(session);
app.use(session({
  store: new MongoStore({ mongooseConnection: mongoose.connection }),
});
```
but the same error occurs.

It seems like my packages are up-to-date:

```
    "express": "^4.17.1",
    "express-session": "^1.17.1",
    "connect-mongo": "^3.2.0",
    "mongoose": "^5.10.5",
```

Thanks for the help.

**Comment by augnustin** [comment]
Apparently this single line of code generates the warning:

```
require('connect-mongo')(require('express-session'))
```

**Comment by mingchuno** [comment]
@augnustin I am currently rewriting the repo using Typescript and hope to solve those legacy issues once and for all 🙏🏻

**Comment by mingchuno** [comment]
@augnustin I have just rewrite the code using TS and published a new version! Can you please help me try it out to see of it fix your issue? https://www.npmjs.com/package/connect-mongo

**Comment by jeroentvb** [comment]
This one is not solved yet. Also getting the error after upgrading.

Package versions
```json
"connect-mongo": "^4.1.0",
"dotenv": "^8.2.0",
"express": "^4.17.1",
"express-session": "^1.17.1",
```

**Comment by mingchuno** [comment]
@jeroentvb What is the warning? Can you show me?
Also, here is a simple setup that you can reference: https://github.com/jdesboeufs/connect-mongo/blob/master/example/index.js

**Comment by mingchuno** [comment]
I have fixed this in https://github.com/jdesboeufs/connect-mongo/commit/37e8d3200e1ac37ad35b0ea2c39e51abb67974b4
at `develop` branch. Will cut a release when I group the bug fixes.

**Comment by ceecko** [comment]
@mingchuno This is still present in 4.2.2

**Comment by mingchuno** [comment]
@ceecko Can you providee reproduceable example?

**Comment by ceecko** [comment]
I'm sorry for the confusion. This was coming from the mongoose instead of connect-mongo.

**Comment by mingchuno** [comment]
@ceecko ??? Can you provide more details?

**Comment by ceecko** [comment]
With mongoose `5.11.18` and node `14.15.1` you can run

```
require('mongoose')
```

To get
```
(node:8028) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by jeroentvb** [comment]
I have traced the warning back to the mongodb package. It is fixed by this commit, which hasn't been included in a release yet https://github.com/mongodb/node-mongodb-native/commit/d67ffa7a2e3f86734c7e9b6944aab1d765b9e75e

**Comment by jeroentvb** [comment]
For my project, this isn't an issue coming from `connect-mongo`. Downgrading `mongodb` in my package.json to v3.6.3 solves it.

**Comment by mingchuno** [comment]
https://github.com/jdesboeufs/connect-mongo/blob/72538719a85392754415318b73bdd336f161ea6d/package.json#L64
I am pinning `3.6.3` too
