### ISSUE TITLE
"Unable to find the session to touch" error message

### ISSUE THREAD

**Issue by D-32** [jdesboeufs/connect-mongo#449]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
When I set something in the user's session I get the following error in the console:

```
(node:29342) UnhandledPromiseRejectionWarning: TypeError: callback is not a function
    at /Users/[...]/node_modules/connect-mongo/src/lib/MongoStore.ts:326:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:29342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29342) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Everything still gets stored correctly though.

MongoStore.ts:326:
```
return callback(new Error('Unable to find the session to touch'));
```

Any ideas why this might be happening?

- **Other information** 
`connect-mongo` version: 4.6.0
`mongodb` version: 4.1.0
node: v14.17.1 (but also happening in v12)

Thanks!

**Comment by mingchuno** [comment]
Might relate to #351

**Comment by D-32** [comment]
I'm still having this issue dear stale bot
