### ISSUE TITLE
"Cannot find module 'mongodb'" in Docker

### ISSUE THREAD

**Issue by Spown** [jdesboeufs/connect-mongo#452]
- **I'm submitting a bug report**

- **Summary**
  When this module is used anywhere in the project (not only as a direct dependency, but a level deeper) and it is built as docker image, the bild lacks mongodb dep module and the resulting container fails:

```
Error: Cannot find module 'mongodb'
Require stack:
- /app/node_modules/connect-mongo/build/main/lib/MongoStore.js
- /app/node_modules/connect-mongo/build/main/index.js
- /app/node_modules/foobar/platform.js
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/app/node_modules/connect-mongo/build/main/lib/MongoStore.js:28:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/app/node_modules/connect-mongo/build/main/index.js:5:38)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
  connect-mongo@4.6.0; Docker engine uses [DOCKER_BUILDKIT: 1](https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds); image is based on [node:14](/nodejs/docker-node/blob/b36041b26d8423f1838fb8232411a12f882cbb6a/14/stretch/Dockerfile).

  It seems it has something to do with the fact, that ``mongodb`` is a peerDep here.

thnx in advance

**Comment by Spown** [comment]
nvm
