### ISSUE TITLE
Can't reuse an exisiting native mongo instance 

### ISSUE THREAD

**Issue by Mohamed-kamel91** [jdesboeufs/connect-mongo#461]
hi, 
I am trying to connect express session to my native mongo store by reusing the existing mongo client instance, but no matter how much i try, it never seem to work at all.
when i run my app , i always end up with this error

Assertion failed: You must provide either mongoUrl|clientPromise|client in options
Error: Cannot init client. Please provide correct options
    at new MongoStore (D:\code\clients\development\Trendy-Toys\server\node_modules\connect-mongo\src\lib\MongoStore.ts:196:13)
    at Function.create (D:\code\clients\development\Trendy-Toys\server\node_modules\connect-mongo\src\lib\MongoStore.ts:214:12)
    at Object.<anonymous> (D:\code\clients\development\Trendy-Toys\server\src\config\sessionStore.ts:11:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (D:\code\clients\development\Trendy-Toys\server\node_modules\ts-node\src\index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (D:\code\clients\development\Trendy-Toys\server\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)

**This my express session in app.js file:** 
```
import sessionStore from './config/sessionStore';

const sessionOptions = {
  secret: env.SESSION_SECRET,
  resave: false,
  saveUninitialized: true,
  store: sessionStore,
  cookie: {
    secure: false,
    name: "session_id",
    sameSite: false,
    httpOnly: true,
    maxAge:  10 * 1000,
  },
};

// set express session store
app.use(session(sessionOptions));
```

**This is sessionStore file:**
I am importing my mongodb instance from a seperate file 
```
import MongoStore from 'connect-mongo';
import env from '.';
import { client } from '../database/db';

const sessionStore = MongoStore.create({
  client,
  collectionName: "sessions",
});

export default sessionStore;

```

**versions:** 
- express: 4.17.1
- express-session": 1.17.3
- connect-mongo: 4.6.0
- mongodb: 4.1.1

I'd apprecite if anyone can help me with this issue. Thanks

**Comment by YasharF** [comment]
Do you still have this issue with the latest versions of the packages from npm repo?  If not, can we close this issue?

**Comment by Mohamed-kamel91** [comment]
I haven’t checked this again since it was a long time ago, and I didn’t receive any replies back then. We can close this issue.
