### ISSUE TITLE
Setting Stringify, serialize and unserialize results in error

### ISSUE THREAD

**Issue by bramvbilsen** [jdesboeufs/connect-mongo#476]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
When setting the `stringify`, `serialize` or `unserialize` options, an error is thrown: Cannot set headers after they are sent to the client. For example, the following works just fine:
```ts
const sessionStore = MongoStore.create({
    mongoUrl: "mongodb://127.0.0.1:27017/databaseX",
    collectionName: "user_sessions",
});
```
But, setting the following results in an the error:
```ts
const sessionStore = MongoStore.create({
    mongoUrl: "mongodb://127.0.0.1:27017/databaseX",
    collectionName: "user_sessions",
    stringify: false
});
```
Because of this, I tried to do this explicitely using the `serialize` option:
```ts
const sessionStore = MongoStore.create({
    mongoUrl: "mongodb://127.0.0.1:27017/databaseX",
    collectionName: "user_sessions",
    serialize: (d) => d,
});
```
This results in the same error.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
The exact error is as follows:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/Users/bramvanbilsen/Documents/Work/TAG/CAP/core/server/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/Users/bramvanbilsen/Documents/Work/TAG/CAP/core/server/node_modules/express/lib/response.js:174:12)
    at ServerResponse.call (/Users/bramvanbilsen/Documents/Work/TAG/CAP/core/server/node_modules/express/lib/response.js:278:15)
    at ServerResponse.error (file:///Users/bramvanbilsen/Documents/Work/TAG/CAP/core/server/src/middleware/responseExtensions.ts:23:25)
    at errorHandler (file:///Users/bramvanbilsen/Documents/Work/TAG/CAP/core/server/src/middleware/errorHandling.ts:13:16)
    at newFn (/Users/bramvanbilsen/Documents/Work/TAG/CAP/core/server/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/Users/bramvanbilsen/Documents/Work/TAG/CAP/core/server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/bramvanbilsen/Documents/Work/TAG/CAP/core/server/node_modules/express/lib/router/index.js:326:13) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by bramvbilsen** [comment]
Upon debugging this more, I found that the issue is due to the following line:
https://github.com/jdesboeufs/connect-mongo/blob/962c7db8afb14778ef6e3530f0ed9e4edff47ce9/src/lib/MongoStore.ts#L385
My session data has an `ObjectId` and when trying to save this to mongo, it complains about the BSON version not being supported:
```
BSONVersionError: Unsupported BSON version, bson types must be from bson 6.x.x
```
