### ISSUE TITLE
Error: Error setting TTL index on collection : sessions

### ISSUE THREAD

**Issue by ariporad** [jdesboeufs/connect-mongo#65]
Hi,
When My App Tries To Connect To The DB I Get This Error: 

```
/Users/Ari/Dev/ArisGame/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:529
    throw err;
          ^
Error: Error setting TTL index on collection : sessions
at module.exports._get_collection (/Users/Ari/Dev/ArisGame/node_modules/connect-mongo/lib/connect-mongo.js:137:23)
at Db.ensureIndex (/Users/Ari/Dev/ArisGame/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1227:28)
at Db.indexInformation (/Users/Ari/Dev/ArisGame/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1371:30)
at Cursor.toArray (/Users/Ari/Dev/ArisGame/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:156:22)
at Cursor.nextObject.self.queryRun (/Users/Ari/Dev/ArisGame/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:611:39)
at Cursor.close (/Users/Ari/Dev/ArisGame/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:939:5)
at Cursor.nextObject.commandHandler (/Users/Ari/Dev/ArisGame/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:611:21)
at Db._executeQueryCommand (/Users/Ari/Dev/ArisGame/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1709:18)
at g (events.js:192:14)
at EventEmitter.emit (events.js:126:20)
```

I'm Sorry,
This Is All I Really Know

**Comment by dparise** [comment]
http://stackoverflow.com/a/22698992

**Comment by htxuankhoa** [comment]
Hi everyone, I tried to install traider.io in my local machine and I also met this error: 
```
Error: Error setting TTL index on collection : sessions
...
```

After searched, as I know because the version of connect-mongo & mongodb is not compatible. So, in my case, I re-installed mongodb with this version & it works:
```
npm install mongodb@1.4.x
```

Hope this help for someone like me :)

**Comment by TimePower** [comment]
@htxuankhoa It works, Very thank you!!!

**Comment by my1GitHub** [comment]
Hi, everyone.this error:
connect to mongo success
{ [MongoError: driver is incompatible with this server version] name: 'MongoError' }
E:\nodeProject\testProjectEJS\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\connection\base.js:242
        throw message;
              ^
Error: Error setting TTL index on collection : sessions
    at E:\nodeProject\testProjectEJS\node_modules\connect-mongo\lib\connect-mongo.js:162:23
    at E:\nodeProject\testProjectEJS\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1430:36
    at __executeInsertCommand (E:\nodeProject\testProjectEJS\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1829:12)
    at Db._executeInsertCommand (E:\nodeProject\testProjectEJS\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1930:5)
    at E:\nodeProject\testProjectEJS\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1427:14
    at E:\nodeProject\testProjectEJS\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1560:7
    at E:\nodeProject\testProjectEJS\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\cursor.js:162:16
    at commandHandler (E:\nodeProject\testProjectEJS\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\cursor.js:706:16)
    at E:\nodeProject\testProjectEJS\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1806:9
    at Server.Base._callHandler (E:\nodeProject\testProjectEJS\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\connection\base.js:442:41)

and this is my package
    "body-parser": "^1.13.2",
    "connect-mongo": "^0.4.1",
    "cookie-parser": "^1.3.5",
    "debug": "~2.2.0",
    "ejs": "~2.4.1",
    "express": "~4.13.4",
    "express-session": "^1.13.0",
    "mongodb": "^2.2.8",
    "morgan": "~1.7.0",
    "serve-favicon": "~2.3.0"
How can i to sovle it?

**Comment by jdesboeufs** [comment]
Hello,

You should upgrade your connect-mongo version!

**Comment by staminna** [comment]
@jdesboeufs Which released version was the first to fix this? The more the latest with updates, the more it breaks my other dependencies.
My package.json:
"connect-mongo": "~0.4.1",
"mongoose": "~4.5.10",
"mongoose-integer": "^0.1.1",
